import Link from 'next/link'
import './globals.css'
import { Rubik } from 'next/font/google'
import Navbar from './components/Navbar'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={rubik.className}>
        <Navbar className= "flex flex-row gap-7 items-['flex-start']" />
        {children}
        </body>
    </html>
  )
}
